package ui;

import javax.swing.JOptionPane;
import dao.MedicamentoDAO;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import model.Medicamento;

public class AddMedFrame extends javax.swing.JFrame {

    public AddMedFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        fechaVLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        stockTextField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        selectFechaV = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("addFrame"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        nombreLabel.setBackground(new java.awt.Color(0, 0, 0));
        nombreLabel.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreLabel.setText("Nombre:");

        stockLabel.setBackground(new java.awt.Color(0, 0, 0));
        stockLabel.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        stockLabel.setForeground(new java.awt.Color(0, 0, 0));
        stockLabel.setText("Stock:");

        fechaVLabel.setBackground(new java.awt.Color(0, 0, 0));
        fechaVLabel.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        fechaVLabel.setForeground(new java.awt.Color(0, 0, 0));
        fechaVLabel.setText("Fecha de Vencimiento:");

        stockTextField.setText("0");

        addBtn.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        addBtn.setText("Agregar");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        cancelarButton.setText("Cerrar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        selectFechaV.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn)
                        .addGap(37, 37, 37)
                        .addComponent(cancelarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(132, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(nombreLabel)
                            .addComponent(stockLabel)
                            .addComponent(fechaVLabel))
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(nombreTextField)
                            .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectFechaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaVLabel)
                    .addComponent(selectFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(cancelarButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        selectFechaV.setCalendar(new GregorianCalendar());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String nombre = nombreTextField.getText();
        int stock = Integer.parseInt(stockTextField.getText());

        SimpleDateFormat fechaFormato = new SimpleDateFormat("yyyy-MM-dd");
        String fechaVencimiento = fechaFormato.format(selectFechaV.getDate());

        if (!nombre.equals("") && !fechaVencimiento.equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea guardar este medicamento?", "Confirmación", JOptionPane.YES_NO_OPTION);

            if (JOptionPane.YES_OPTION == confirmacion) {
                MedicamentoDAO medDAO = new MedicamentoDAO();
                Medicamento med = new Medicamento();

                med.setNombre(nombre);
                med.setStock(stock);
                med.setFechaVencimiento(fechaVencimiento);

                medDAO.insert(med);

                JOptionPane.showMessageDialog(this, "¡El medicamento se ha guardado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                nombreTextField.setText("");
                stockTextField.setText("0");
                selectFechaV.setCalendar(new GregorianCalendar());
            }
        } else {
            JOptionPane.showMessageDialog(this, "¡Los campos Nombre y/o Fecha de vencimiento están vacíos!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        MainFrame p = new MainFrame();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setDefaultCloseOperation(p.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel fechaVLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private com.toedter.calendar.JDateChooser selectFechaV;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JTextField stockTextField;
    // End of variables declaration//GEN-END:variables
}
